name: Pipeline (Build & Test)
on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Test-and-Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Build Pipe
        working-directory: ./JHotDraw
        run: mvn --batch-mode --update-snapshots verify 

      - name: Test Pipe
        working-directory: ./JHotDraw
        run: mvn test 
