name: CI Pipeline
on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Build Pipe
        working-directory: ./JHotDraw
        run: mvn --batch-mode --update-snapshots verify
        
  Test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Testing pipeline
        working-directory: ./JHotDraw
        run: mvn test 
